-- CP_FXBrowser — auto-generated config
return {
  auto_open = false,
  post_insert = {
    debug = false,
    enabled = true,
    random_count = 3,
    randomize_base = true,
    randomize_invert = true,
    randomize_range = true,
    randomize_xy = true,
    select_mode = "all_cont"
  },
  rand_count = 4,
  rand_fav_only = false,
  rand_from_visible = true,
  rand_replace = true,
  recents = {
    "kHs Phase Distortion (Kilohearts)",
    "kHs Nonlinear Filter (Kilohearts)",
    "kHs Flanger (Kilohearts)",
    "kHs Frequency Shifter (Kilohearts)",
    "kHs Ring Mod (Kilohearts)",
    "kHs Chorus (Kilohearts)",
    "kHs Resonator (Kilohearts)",
    "kHs Haas (Kilohearts)",
    "kHs Reverb (Kilohearts)",
    "kHs Distortion (Kilohearts)",
    "kHs Delay (Kilohearts)",
    "kHs Ladder Filter (Kilohearts)",
    "kHs Phaser (Kilohearts)",
    "kHs Filter (Kilohearts)",
    "kHs Reverser (Kilohearts)",
    "kHs Pitch Shifter (Kilohearts)",
    "kHs Dual Delay (Kilohearts)",
    "kHs Bitcrush (Kilohearts)",
    "kHs Formant Filter (Kilohearts)",
    "kHs Ensemble (Kilohearts)",
    "PrimalTap (Soundtoys)",
    "Tremolator (Soundtoys)",
    "FilterFreak2 (Soundtoys)",
    "Little AlterBoy (Soundtoys)",
    "Little Plate (Soundtoys)",
    "Decapitator (Soundtoys)",
    "Radiator (Soundtoys)",
    "Sie-Q (Soundtoys)",
    "PanMan (Soundtoys)",
    "PhaseMistress (Soundtoys)"
  },
  sort_mode = "az",
  split_left = 0.5,
  tabs = {
    {
      name = "kHss",
      plugin_names = {
        "kHs Compressor (Kilohearts)",
        "kHs Chorus (Kilohearts)",
        "kHs 3-Band EQ (Kilohearts)",
        "kHs Bitcrush (Kilohearts)",
        "kHs Channel Mixer (Kilohearts)",
        "kHs Clipper (Kilohearts)",
        "kHs Comb Filter (Kilohearts)",
        "kHs Convolver (Kilohearts)",
        "kHs Delay (Kilohearts)",
        "kHs Distortion (Kilohearts)",
        "kHs Dual Delay (Kilohearts)",
        "kHs Dynamics (Kilohearts)",
        "kHs Ensemble (Kilohearts)",
        "kHs Filter (Kilohearts)",
        "kHs Filter Table (Kilohearts)",
        "kHs Flanger (Kilohearts)",
        "kHs Formant Filter (Kilohearts)",
        "kHs Frequency Shifter (Kilohearts)",
        "kHs Gain (Kilohearts)",
        "kHs Gate (Kilohearts)",
        "kHs Haas (Kilohearts)",
        "kHs Ladder Filter (Kilohearts)",
        "kHs Limiter (Kilohearts)",
        "kHs Nonlinear Filter (Kilohearts)",
        "kHs Phase Distortion (Kilohearts)",
        "kHs Phaser (Kilohearts)",
        "kHs Pitch Shifter (Kilohearts)",
        "kHs Resonator (Kilohearts)",
        "kHs Reverb (Kilohearts)",
        "kHs Reverser (Kilohearts)",
        "kHs Ring Mod (Kilohearts)",
        "kHs Shaper (Kilohearts)",
        "kHs Shaper Table (Kilohearts)",
        "kHs Stereo (Kilohearts)",
        "kHs Tape Stop (Kilohearts)",
        "kHs Trance Gate (Kilohearts)",
        "kHs Transient Shaper (Kilohearts)"
      }
    },
    {
      name = "test",
      plugin_names = {
        "kHs Filter Table (Kilohearts)"
      }
    },
    {
      name = "cool",
      plugin_names = {
        "kHs Bitcrush (Kilohearts)",
        "kHs Chorus (Kilohearts)",
        "kHs Delay (Kilohearts)",
        "kHs Distortion (Kilohearts)",
        "kHs Dual Delay (Kilohearts)",
        "kHs Ensemble (Kilohearts)",
        "kHs Filter (Kilohearts)",
        "kHs Flanger (Kilohearts)",
        "kHs Formant Filter (Kilohearts)",
        "kHs Frequency Shifter (Kilohearts)",
        "kHs Haas (Kilohearts)",
        "kHs Ladder Filter (Kilohearts)",
        "kHs Nonlinear Filter (Kilohearts)",
        "kHs Phase Distortion (Kilohearts)",
        "kHs Phaser (Kilohearts)",
        "kHs Pitch Shifter (Kilohearts)",
        "kHs Resonator (Kilohearts)",
        "kHs Reverb (Kilohearts)",
        "kHs Reverser (Kilohearts)",
        "kHs Ring Mod (Kilohearts)"
      }
    }
  },
  type_filter = "T:cool"
}
