-- CP_MediaExplorer — auto-generated config
return {
  accordion = false,
  autoplay = true,
  carry_rate_pitch = false,
  carry_volume = false,
  collections = {
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  },
  expanded = {
    "E:/PARA/Resources/Sound Bank/Sound Library/Boom Library/Boom Library Riparian Zones",
    "E:/PARA/Resources/Sound Bank",
    "E:/PARA/Resources/Sound Bank/Music Samples",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Cymbals/Hi Hats Open",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Cymbals/Hi Hats Closed",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1",
    "E:/PARA/Resources/Sound Bank/Sound Library/My Library/Chez Arnaud",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Cymbals",
    "E:/PARA/Resources/Sound Bank/Music Samples/Antidote Audio - Dubstep",
    "E:/PARA/Resources/Sound Bank/Music Samples/FatLoud - Drum Hits Collection 2/WAV (24 bit)",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1",
    "E:/PARA/Resources/Sound Bank/Sound Library/Boom Library/Boom Library Riparian Zones/Riparian Zones Stereo",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab"
  },
  favorites = {
    "fx|VST3: MFlanger (MeldaProduction)"
  },
  list_scroll = 8266,
  loop = false,
  pitch = 0,
  rate = 1,
  recents = {
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Cymbals/Hi Hats Open/KSHMR Hi Hats Open 03.aif",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Cymbals/Hi Hats Closed/KSHMR Hi Hats Closed 01.aif",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Snares/Tight Snares/KSHMR Tight Snare 01.aif",
    "E:/PARA/Resources/Sound Bank/Music Samples/ASHRAM - Afro House Downtempo/Oneshots/Kickdrum/AS_AHD3_Kick_1.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_160_Hole2.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_160_Hole1.wav",
    "E:/PARA/Resources/Sound Bank/Sound Library/Boom Library/Boom Library Riparian Zones/Riparian Zones Stereo/QP15 1816 Riparian temp East forest trickle morning songbirds V1.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/FatLoud - Drum Hits Collection 2/WAV (24 bit)/Snare Drums/SD_FDHC2_003.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/FatLoud - Drum Hits Collection 2/WAV (24 bit)/Snare Drums/SD_FDHC2_001.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/FatLoud - Drum Hits Collection 2/WAV (24 bit)/Snare Drums/SD_FDHC2_006.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/FatLoud - Drum Hits Collection 2/WAV (24 bit)/Snare Drums/SD_FDHC2_009.wav",
    "E:/PARA/Resources/Sound Bank/Sound Library/My Library/Chez Gouss/ROCKCrsh_Debris Brick Gravel_CP_NONE.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Soltan Sample Pack Vol. 2/SOLTAN_drums/SOLTAN_drum_loops/SOLTAN_drum_loops/SOLTAN_drum_loop_09_time_128.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Soltan Sample Pack Vol. 2/SOLTAN_drums/SOLTAN_drum_loops/SOLTAN_drum_loops/SOLTAN_drum_loop_07_faster_90.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.2/Drums/Kicks/Punchy Kicks/KSHMR Punchy Kick 12 (E).wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_170_Trapper1.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-jazz-groove-samples/Drum_Loops/Cymbal_loop05(185BPM).wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_150_dVision.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_dnb_ring_170.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Fox Samples - Reggae Radio/FS_RR_KIT_03_80BPM_KEYA#MINOR_FULLMIX.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-05.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_158_Idmatic.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_154_Hash.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-lounge-samples/Kit02 85bpm/Drums/Beats A/BeatK02A 85-03.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-lounge-samples/Kit02 85bpm/Drums/Beats A/BeatK02A 85-01.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Maracas [MA]/E808_MA-07.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Maracas [MA]/E808_MA-06.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Maracas [MA]/E808_MA-04.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Cowbell [CB]/E808_CB-02.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-06.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-01.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-03.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-02.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Sample Magic - Dream Pop/one-shots/bass_one-shots/dp_bass_jazz_short_E.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Sample Magic - Dream Pop/one-shots/bass_one-shots/dp_bass_jazz_long_E.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Just Blaze Drumkit/JUST_drums/JUST_kicks/JUST_kick_executive.wav",
    "E:/PARA/Resources/Sound Bank/Sound Library/Boom Library/Boom Library Urban Europe/Urban Europe Stereo/AMBCnst_Downtown Car Park Construction Germany_B00M_3DS05_2.0.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_165_Harder1.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_160_Pyramid2.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_160_Hole3.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_159_Paranoya.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Origin Sound - VINTAGE VIBES/one_shots/drum_hits/hihats/OS_VV_hihat_softy.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Origin Sound - VINTAGE VIBES/one_shots/drum_hits/hihats/OS_VV_hihat_plate.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Origin Sound - VINTAGE VIBES/one_shots/drum_hits/hihats/OS_VV_hihat_machine.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Origin Sound - VINTAGE VIBES/one_shots/drum_hits/hihats/OS_VV_hihat_live.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Origin Sound - VINTAGE VIBES/one_shots/drum_hits/hihats/OS_VV_hihat_light.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Origin Sound - VINTAGE VIBES/one_shots/drum_hits/hihats/OS_VV_hihat_coils.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Deep Jazz House Vocals/GIA_WAV_LOOPS/GIA_DRUM_LOOPS/GIA_124_Shaft_Of_Light_Fill_2.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Deep Jazz House Vocals/GIA_WAV_LOOPS/GIA_DRUM_LOOPS/GIA_124_Shaft_Of_Light_Top.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Deep Jazz House Vocals/GIA_WAV_LOOPS/GIA_DRUM_LOOPS/GIA_124_Shaft_Of_Light_Kick.wav"
  },
  roots = {
    "E:/PARA/Resources/Sound Bank/Sound Library/Boom Library",
    "E:/PARA/Resources/Sound Bank/Music Samples",
    "E:/PARA/Resources/Sound Bank",
    "C:/Users/Cedric/Videos"
  },
  route_track = false,
  space_transport = false,
  swap_resize = false,
  sync_mult = 1,
  tempo_sync = true,
  use_mediadb = true,
  volume = 0.636364,
  wave_rows = false
}
