-- CP_MediaExplorer — auto-generated config
return {
  accordion = false,
  autoplay = true,
  carry_rate_pitch = false,
  carry_volume = false,
  collections = {
    {
      "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - KRANE Samples Vol 4/KRANE Samples Vol. 4/01_DRUMS/Kicks/KRANE_OverU_Kick.wav"
    },
    {},
    {},
    {},
    {},
    {},
    {}
  },
  expanded = {
    "E:/PARA/Resources/Sound Bank/Music Samples/Ultrasonic - Slap House Essentials Vol.1",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Bighead Sample Pack/KBH_melodic_loops",
    "E:/PARA/Resources/Sound Bank/Music Samples/Vengeance - Synthwave Essentials 1/VSW1 Bassdrum/VSW1 Soft Vintage Kicks",
    "E:/PARA/Resources/Sound Bank/Music Samples/Vengeance - Synthwave Essentials 1/VSW1 Snares/VSW1 Long Snares",
    "E:/PARA/Resources/Sound Bank/Music Samples/Vengeance - Synthwave Essentials 1/VSW1 Snares",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - KRANE Samples Vol 4/KRANE Samples Vol. 4/01_DRUMS",
    "E:/PARA/Resources/Sound Bank/Music Samples/Vengeance - Synthwave Essentials 1/VSW1 Snares/VSW1 Short Snares",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - KRANE Samples Vol 4/KRANE Samples Vol. 4/01_DRUMS/Kicks",
    "E:/PARA/Resources/Sound Bank/Music Samples/Ultrasonic - Slap House Essentials Vol.1/1. Ultrasonic - Kicks"
  },
  favorites = {
    "fx|VST3: MFlanger (MeldaProduction)"
  },
  list_scroll = 942,
  loop = false,
  pitch = 0,
  rate = 1,
  recents = {
    "E:/PARA/Resources/Sound Bank/Music Samples/Ultrasonic - Slap House Essentials Vol.1/1. Ultrasonic - Kicks/Ultrasonic - Slap House Essentials - Kick 09.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Bighead Sample Pack/KBH_melodic_loops/KBH_melodic_loop_arpeggio_chords_130_Dmin.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Sonny D - Drumkit/SONNY_D_fx/SONNY_D_fx_02.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Sonny D - Drumkit/SONNY_D_drums/SONNY_D_drum_loops/SONNY_D_drum_loop_01_133.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Sonny D - Drumkit/SONNY_D_drums/SONNY_D_drum_loops/SONNY_D_drum_loop_08_146.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Sample Magic - House Nation/Wav/drum loops/hn_drm125_base1.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Kick Pack 1/194171__old-waveplay__kick-noisy-kick.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.2/Drums/Cymbals/Hi-Hats Closed/KSHMR Hi Hats Closed 01.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.2/Drums/Snares/Tight Snares/KSHMR Tight Snare 01 (B).wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.2/Drums/Kicks/Punchy Kicks/KSHMR Punchy Kick 06 (D#).wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.2/Drums/Kicks/Punchy Kicks/KSHMR Punchy Kick 01 (A#).wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Cymbals/Hi Hats Open/KSHMR Hi Hats Open 03.aif",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Cymbals/Hi Hats Open/KSHMR Hi Hats Open 01.aif",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Cymbals/Hi Hats Closed/KSHMR Hi Hats Closed 01.aif",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.1/Splice Sounds of KSHMR Vol 1/KSHMR Snares/Tight Snares/KSHMR Tight Snare 01.aif",
    "E:/PARA/Resources/Sound Bank/Music Samples/ASHRAM - Afro House Downtempo/Oneshots/Kickdrum/AS_AHD3_Kick_1.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_160_Hole2.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_160_Hole1.wav",
    "E:/PARA/Resources/Sound Bank/Sound Library/Boom Library/Boom Library Riparian Zones/Riparian Zones Stereo/QP15 1816 Riparian temp East forest trickle morning songbirds V1.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/FatLoud - Drum Hits Collection 2/WAV (24 bit)/Snare Drums/SD_FDHC2_003.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/FatLoud - Drum Hits Collection 2/WAV (24 bit)/Snare Drums/SD_FDHC2_001.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/FatLoud - Drum Hits Collection 2/WAV (24 bit)/Snare Drums/SD_FDHC2_006.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/FatLoud - Drum Hits Collection 2/WAV (24 bit)/Snare Drums/SD_FDHC2_009.wav",
    "E:/PARA/Resources/Sound Bank/Sound Library/My Library/Chez Gouss/ROCKCrsh_Debris Brick Gravel_CP_NONE.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Soltan Sample Pack Vol. 2/SOLTAN_drums/SOLTAN_drum_loops/SOLTAN_drum_loops/SOLTAN_drum_loop_09_time_128.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Soltan Sample Pack Vol. 2/SOLTAN_drums/SOLTAN_drum_loops/SOLTAN_drum_loops/SOLTAN_drum_loop_07_faster_90.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Sounds of KSHMR Vol.2/Drums/Kicks/Punchy Kicks/KSHMR Punchy Kick 12 (E).wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_170_Trapper1.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-jazz-groove-samples/Drum_Loops/Cymbal_loop05(185BPM).wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_150_dVision.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_dnb_ring_170.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Fox Samples - Reggae Radio/FS_RR_KIT_03_80BPM_KEYA#MINOR_FULLMIX.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-05.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_158_Idmatic.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_154_Hash.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-lounge-samples/Kit02 85bpm/Drums/Beats A/BeatK02A 85-03.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-lounge-samples/Kit02 85bpm/Drums/Beats A/BeatK02A 85-01.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Maracas [MA]/E808_MA-07.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Maracas [MA]/E808_MA-06.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Maracas [MA]/E808_MA-04.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Cowbell [CB]/E808_CB-02.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-06.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-01.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-03.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Musicradar/musicradar-808-samples/Hits/Bass Drum [BD]/E808_BD[long]-02.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Sample Magic - Dream Pop/one-shots/bass_one-shots/dp_bass_jazz_short_E.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Sample Magic - Dream Pop/one-shots/bass_one-shots/dp_bass_jazz_long_E.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Splice Sounds - Just Blaze Drumkit/JUST_drums/JUST_kicks/JUST_kick_executive.wav",
    "E:/PARA/Resources/Sound Bank/Sound Library/Boom Library/Boom Library Urban Europe/Urban Europe Stereo/AMBCnst_Downtown Car Park Construction Germany_B00M_3DS05_2.0.wav",
    "E:/PARA/Resources/Sound Bank/Music Samples/Drum n Bass/Rhythm Lab/cw_165_Harder1.wav"
  },
  roots = {
    "E:/PARA/Resources/Sound Bank/Sound Library/Boom Library",
    "E:/PARA/Resources/Sound Bank/Music Samples",
    "E:/PARA/Resources/Sound Bank",
    "C:/Users/Cedric/Videos"
  },
  route_track = false,
  space_transport = false,
  swap_resize = false,
  sync_mult = 1,
  tempo_sync = true,
  use_mediadb = true,
  volume = 0.636364,
  wave_rows = false
}
